### ISSUE TITLE
Checklist

### ISSUE THREAD

**Issue by MrVii** [MrVii/RSPEmails#1]
Each of these items will need the following to be done: Logo changed to the RSP logo, Text Changed to match the type of email it is(doesn't need to be perfect), Remove anything additional and unnecessary.

- [x] Registration Email

- [x] Account Confirmation Email

- [x] Account Welcome Email
When Ready to be reviewed just message complete in this issue and ill check it out

**Comment by Artamist** [comment]
Complete
